### ISSUE TITLE
unnecessary horizontal scrool bar on Post page

### ISSUE THREAD

**Issue by dengere** [Devahoy/ghostahoy#3]
post page always has horizontal scroolbar (chrome version 44.0.2403.107 m).
it doesn't care necessary or unnecessary, its look like ugly for short content display scrool for nothing. 

body { overflow-x: hidden; }

could fix

**Comment by Phonbopit** [comment]
thank you for let me know but I don't get it, can you please attach screenshot?

Thanks.

**Comment by dengere** [comment]
when you use page code utf-8 or another language (as mine turkish windows-1254), ghost engine left   special delimiter character  after >default . it is issue of ghost but anyway page has suddenly horizontal scrool while doesn't need it. 
if you let css like this something
body { overflow-x: hidden; }
stop to show horizontal scrool, you know noone need it.
